---
- name: Get hostname from hosts
  hosts: all
  gather_facts: no
  vars:
    ansible_user: admin
    ansible_password: ansible1
    ansible_become: yes
    ansible_become_password: ansible1
    ansible_connection: network_cli

  tasks:
    - name: Gather facts from Cisco switch
      cisco.ios.ios_facts:

    - name: Display hostname
      debug:
        var: ansible_net_hostname
