---
- name: Display and Configure Basic Settings
  hosts: all
  gather_facts: no
  vars:
    ansible_user: admin
    ansible_password: ansible1
    ansible_become: yes
    ansible_become_password: ansible1
    ansible_connection: network_cli

  tasks:
    - name: Show current hostname
      ios_command:
        commands:
          - show running-config | include hostname
      register: hostname_output

    - name: Display hostname
      debug:
        var: hostname_output.stdout[0]

    - name: Show current domain name
      ios_command:
        commands:
          - show running-config | include ip domain-name
      register: domain_output

    - name: Display domain name
      debug:
        var: domain_output.stdout[0]

    - name: Show SSH configuration
      ios_command:
        commands:
          - show ip ssh
      register: ssh_output

    - name: Display SSH configuration
      debug:
        var: ssh_output.stdout[0]

