---
- name: CONFIGURE VLANs
  hosts: all
  gather_facts: false
  vars:
    ansible_user: admin
    ansible_password: ansible1
    ansible_connection: network_cli
    ansible_become: yes
    ansible_become_password: ansible1

  tasks:
    - name: CREATE VLANs
      ios_config:
        lines:
          - vlan 10
          - vlan 20
      register: output

    - name: DISPLAY OUTPUT
      debug:
        var: output.stdout

