---
- name: Grab Show Run and Backup Config
  hosts: all
  gather_facts: no
  vars:
    ansible_user: admin
    ansible_password: ansible1
    ansible_become_password: ansible1
    ansible_connection: network_cli
    ansible_become: yes
    backup_dir: "/home/cvandong/cisco-automation/backups"  # Backup directory path

  tasks:
    - name: Grab Show Run
      ios_command:
        commands:
          - show running-config
      register: running_config

    - name: Save Running-Config to Local File
      copy:
        content: "{{ running_config.stdout[0] }}"
        dest: "{{ backup_dir }}/{{ inventory_hostname }}_running_config.txt"

    - name: Print Backup Confirmation
      debug:
        msg: "Backup of {{ inventory_hostname }} saved successfully to {{ backup_dir }}/{{ inventory_hostname }}_running_config.txt."

